src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <label>OrderItem</label>
    <nameField>
        <displayFormat>OrderItem-{0000}</displayFormat>
        <label>OrderItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestOrderItemTriggerHandler.cls
@IsTest
public with sharing class TestOrderItemTriggerHandler {
    @TestSetup
     static void testSetup() {
        Integer count = 3;
        List<Product__c> products     = TestFactory.createProducts(count, 10, 'Test');
        List<Account> accounts        = TestFactory.createAccounts(count);
        List<Order__c> orders         = TestFactory.createOrders(accounts);
        List<OrderItem__c> orderItems = TestFactory.createOrderItems(products, orders , count);

    }

    @IsTest
    private static void ProcessAfterInsertTest() {
        List<Order__c> orders = [
                SELECT
                        Name, AccountId__c, TotalProductCount__c, TotalPrice__c
                FROM
                        Order__c
                LIMIT
                        10000
        ];
        for (Order__c order : orders) {
            System.assertEquals(3, order.TotalProductCount__c);
            System.assertEquals(90, order.TotalPrice__c);
        }
    }
}