src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <displayFormat>OrderItem-{0000}</displayFormat>
        <label>OrderItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderItemTriggerHandler.cls
public with sharing class OrderItemTriggerHandler {

    public static void processAfterInsert(List<OrderItem__c> orderItems) {
        updateOrder(orderItems);
    }

    private static void updateOrder(List<OrderItem__c> orderItems) {
        Map<Id, List<OrderItem__c>> orderItemMap = getOrderIdsMap(orderItems);
        List<Order__c> existingOrders = gerOrderObject(orderItemMap);

        for (Order__c order : existingOrders) {
            setOrderFields(order, orderItemMap);
        }
        update existingOrders;
    }

    private static Map<Id, List<OrderItem__c>> getOrderIdsMap(List<OrderItem__c> orderItems) {
        Map<Id, List<OrderItem__c>> orderItemMap = new Map<Id, List<OrderItem__c>>();

        for (OrderItem__c orderItem : orderItems) {
            Id OrderId = orderItem.OrderId__c;

            if (orderItemMap.containsKey(OrderId)) {
                List<OrderItem__c> keyValue = orderItemMap.get(OrderId);
                keyValue.add(orderItem);
                orderItemMap.put(OrderId, keyValue);
            } else {
                orderItemMap.put(OrderId, new List<OrderItem__c>{orderItem});
            }
        }

        return orderItemMap;
    }

    private static Order__c setOrderFields(Order__c order, Map<Id, List<OrderItem__c>> orderItemMap) {
        List<OrderItem__c> orderItems = orderItemMap.get(order.Id);
        order.TotalProductCount__c = orderItems.size();
        Decimal totalPrice         = 0;

        for (OrderItem__c orderItem : orderItems) {
            totalPrice += orderItem.Price__c;
        }
        order.TotalPrice__c = totalPrice;

        return order;
    }

    private static List<Order__c> gerOrderObject(Map<Id, List<OrderItem__c>> orderItemMap) {
        return [
                SELECT
                        TotalProductCount__c, TotalPrice__c
                FROM
                        Order__c
                WHERE
                        Id IN :orderItemMap.keySet()
                LIMIT
                        10000
        ];
    }
}