src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <displayFormat>OrderItem-{0000}</displayFormat>
        <label>OrderItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestFactory.cls
@IsTest
public with sharing class TestFactory {

    public static List<OrderItem__c> createOrderItems(List<Product__c> products, List<Order__c> orders, Integer quantity) {
        List<OrderItem__c> orderItems = new List<OrderItem__c>();
        for (Order__c order : orders) {
            for (Product__c product : products) {
                orderItems.add(new OrderItem__c(
                        OrderId__c   = order.Id,
                        ProductId__c = product.Id,
                        Quantity__c  = quantity,
                        Price__c     = quantity * product.Price__c
                ));
            }
        }
        insert orderItems;

        return orderItems;
    }

    public static List<Order__c> createOrders(List<Account> accounts) {
        List<Order__c> orders = new List<Order__c>();

        for (Account account : accounts) {
            orders.add(new Order__c(
                    AccountId__c = account.Id
            ));
        }
        insert orders;

        return orders;
    }

    public static List<Account> createAccounts(Integer count) {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < count; i++) {
            accounts.add(new Account(
                    Name = 'Test' + i
            ));
        }
        insert accounts;

        return accounts;
    }

    public static List<Product__c> createProducts(Integer count, Decimal price, String name) {
        List<Product__c> products = new List<Product__c>();
        for (Integer i = 0; i < count; i++) {
            products.add(new Product__c(
                    Name = name + i,
                    Description__c = 'Test',
                    Price__c = price
            ));
        }
        insert products;

        return products;
    }
}