src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Сlothes</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Сlock</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Earphones</fullName>
                </value>
                <value>
                    <fullName>Speakers</fullName>
                </value>
                <value>
                    <fullName>Batteries</fullName>
                </value>
                <value>
                    <fullName>Jackets</fullName>
                </value>
                <value>
                    <fullName>T-Shirts</fullName>
                </value>
                <value>
                    <fullName>Shirts</fullName>
                </value>
                <value>
                    <fullName>Sweaters</fullName>
                </value>
                <value>
                    <fullName>Socks</fullName>
                </value>
                <value>
                    <fullName>Mechanical Watches</fullName>
                </value>
                <value>
                    <fullName>Quartz Watches</fullName>
                </value>
                <value>
                    <fullName>Digital Watches</fullName>
                </value>
                <value>
                    <fullName>Sports Watches</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderManagementContainerCtr.cls
public with sharing class OrderManagementContainerCtr {

    @AuraEnabled(cacheable=true)
    public static ResultData getSearchResults(String key, String filterResultString) {
        FilterResult filterResult = (FilterResult)JSON.deserialize(filterResultString, FilterResult.class);
        ResultData result = new ResultData();
        try {
            result.resultJSON = JSON.serialize(getSearchedProducts(key, filterResult));
        } catch (Exception ex) {
            result.status  = Constants.ANSWER_STATUS_ERROR;
            result.message = ex.getMessage();
        }

        return result;
    }

    private static List<Product__c> getSearchedProducts(String key, FilterResult filterResult) {
        String query =  'Select Id, Name, Description__c, Type__c, Family__c, Image__c, Price__c ' +
                        'FROM Product__c ' +
                        getCondition(key, filterResult) +
                        ' LIMIT 50000';

        return ProductSelector.getSearchProducts(query, key);
    }

    private static String getCondition(String key, FilterResult filterResult) {
        return  DBSOQLProcessor.setCondition(
                new List<String>{
                        DBSOQLProcessor.getConditionLike('Name', key),
                        DBSOQLProcessor.getConditionEqual('Family__c', filterResult.family),
                        DBSOQLProcessor.getConditionEqual('Type__c', filterResult.type)
                }
        );

    }

    public class ResultData {
        @AuraEnabled public String status = Constants.ANSWER_STATUS_SUCCESS;
        @AuraEnabled public String message = '';
        @AuraEnabled public String resultJSON;
    }

    public class FilterResult {
        @AuraEnabled public String family;
        @AuraEnabled public String type;
    }
}